### ISSUE TITLE
Nothing happens !

### ISSUE THREAD

**Issue by xkajxkajx** [dotcomboom/Spiffy-Icon-Extractor#2]
After clicking Start ,Nothing happens !

**Comment by dotcomboom** [comment]
It turns out I totally forgot to upload IconExtractor.dll (on which this program was based) when I made the release. I uploaded a new zip for it you can grab at https://github.com/dotcomboom/Icon-Extractor/releases/download/v0.9/Spiffy.Icon.Extractor.zip.

**Comment by xkajxkajx** [comment]
Now it woks perfect.
Thanx a lot.

**Comment by dotcomboom** [comment]
Great to hear! Closing this issue now.
